languageCode = "en"
languageName = "English"
weight = 1
title = "Igor Carvalho"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "My Website"

[author]
name = "Igor Carvalho"
headline = "Software engineering researcher"
links = [ 
  { github = "https://github.com/igorcarvalhh" },
  { email = "contact@lealigor.com" },
  { instagram = "https://www.instagram.com/igor.carvalhh/" },
  { linkedin = "https://www.linkedin.com/in/igor-carvalho-ramos/" },
  { medium = "contact@lealigor.com" },
  { x-twitter = "contact@lealigor.com" },
]
bio = "Software engineering researcher"
image = "photo7.jpg"
