[[main]]
none = "none"

[[main]]
name = "Articles"
pageRef = "articles"
identifier = "GutXv1nEHa"
weight = 9999

[[main]]
name = "About"
pageRef = "bio"
identifier = "GutXv1nsds"
weight = 9999

[[footer]]
none = "none"
