colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
disableImageOptimization = false
disableTextInHeader = false

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "5"
showMoreLink = true
showMoreLinkDest = "/posts"
showHero = true
cardView = false
constrainItemsWidth = true
homepageImage = "featured.png"
layoutBackgroundHeaderSpace = true
layoutBackgroundBlur = true
cardViewScreenWidth = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = true
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showZenMode = true
heroStyle = "background"

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = false
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
